    ALTER TABLE APP_COMMISSION.CE_STG_PRODUCT_TRACKER
MODIFY (
    NAME_PRODUCT              VARCHAR2(255 CHAR),
    PRODUCT_CATEGORY          VARCHAR2(4000 CHAR),
    STATUS                    VARCHAR2(255 CHAR),  -- Changed from 100 to match NAME_PRODUCT_VERSION_STATUS
    SERVICES                  VARCHAR2(4000 CHAR),
    INSURANCE                 VARCHAR2(4000 CHAR),
    NAME_PRODUCT_PROFILE      VARCHAR2(255 CHAR),
    LAST_UPDATED_BY           VARCHAR2(255 CHAR)
);
